name: gameserver (Git Save)

on:
  workflow_dispatch: # 允许网页手动点击触发
  repository_dispatch: # ✅ 允许 Webhook 触发
    types: [start-server] # 你的事件名称

# 赋予写权限，以便提交 cookie.txt
permissions:
  contents: write

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install requests websocket-client selenium selenium-wire blinker==1.7.0

    - name: Run Selenium Script
      env:
        MY_USERNAME: ${{ secrets.MY_USERNAME }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
      run: |
        python main.py

    # 检测并提交 cookie.txt
    - name: Commit and Push Cookie
      run: |
        git config --global user.name "Auto Bot"
        git config --global user.email "bot@github.com"
        
        git add cookie.txt
        
        if git diff --staged --quiet; then
          echo "✅ Cookie 没有变化，跳过提交。"
        else
          echo "🍪 检测到 Cookie 更新，正在推送到仓库..."
          git commit -m "Update cookie.txt [skip ci]"
          git push
        fi
