name: gameserver (Git Save)

on:
  workflow_dispatch: # 允许网页手动点击触发
  repository_dispatch: # ✅ 允许 Webhook 触发
    types: [start-server] # 你的事件名称

# 赋予写权限，以便提交 cookie.txt
permissions:
  contents: write

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: akina005/scripts
          token: ${{ secrets.REPO_TOKEN }}
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        working-directory: scripts/gameserver
        run: |
          pip install requests websocket-client selenium selenium-wire blinker==1.7.0

      - name: Run Selenium Script
        working-directory: scripts/gameserver
        env:
          gameserver_ACCOUNTS: ${{ secrets.gameserver_ACCOUNTS }}
          # 👇 这里的变量名和 Secret 名都改成了带前缀的
          gameserver_PROXY_URL: ${{ secrets.gameserver_PROXY_URL }}
        run: |
          python main.py

      - name: Commit and Push Cookie
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "bot@github.com"
          
          git add scripts/gameserver/cookie.txt
          
          if git diff --staged --quiet; then
            echo "✅ Cookie 没有变化，跳过提交。"
          else
            echo "🍪 检测到 Cookie 更新，正在推送到仓库..."
            git commit -m "Update cookie.txt [skip ci]"
            git push
          fi
