name: x10hosting Login

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'  # 每周五晚上8点

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取私有仓库
        uses: actions/checkout@v4
        with:
          repository: akina005/scripts
          token: ${{ secrets.REPO_TOKEN }}
          path: .

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install
        run: |
          pip install playwright requests
          playwright install firefox
          
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.4
        with:
          stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
          mode: wireguard    # Optional. Support [ wireguard, client ]. Default is wireguard.    
      
      - name: Run
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          X10hosting: ${{ secrets.X10hosting }}
        run: python scripts/X10hosting/login_script.py
